version: '3.9'

services:
  db_postgres:
    image: postgres:15
    container_name: luiza_labs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: luiza_labs_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - luiza_labs_db_pg_data:/var/lib/postgresql/data
    networks:
      - luiza_labs_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: no
    depends_on:
      - db_postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=db_postgres
      - DB_PORT=5432
      - DB_NAME=luiza_labs_db
      - DB_USER=postgres
      - DB_PASSWORD=123456
    networks:
      - luiza_labs_network

volumes:
  luiza_labs_db_pg_data:

networks:
  luiza_labs_network:
    driver: bridge